name: Connector
author: balugaq
description: This is a plugin
main: com.balugaq.connector.Connector
website: https://github.com/balugaq/Connector
version: ${project.version}
api-version: 1.20
commands:
  connector:
    aliases:
      - cf
      - connector
    description: /connector
    usage: /connector <sub>
